name: PHP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  # Setting an environment variable with the value of a configuration variable
  PROJECT_NAME: ${{ vars.PROJECT_NAME }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup PHP with latest versions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: 'Create env file'
        run: |
          echo "repository variable : ${{ vars.PROJECT_NAME }}"
          touch .env
          echo PROJECT_NAME=${{ vars.PROJECT_NAME }} >> .env
          cat .env
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run PHP Script
        working-directory: src
        run: php index.php