name: PHP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP with latest versions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Run PHP Script
        run: php ./src/index.php