name: PHP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  # Setting an environment variable with the value of a configuration variable
  PROJECT_NAME: ${{ vars.PROJECT_NAME }}
  API_KEY: ${{ vars.API_KEY }}
  BITBUCKET_EMAIL: ${{ vars.BITBUCKET_EMAIL }}
  BITBUCKET_TOKEN: ${{ vars.BITBUCKET_TOKEN }}
  CONFLUENCE_SPACEKEY: ${{ vars.CONFLUENCE_SPACEKEY }}
  CONFLUENCE_URL: ${{ vars.CONFLUENCE_URL }}
  GITHUB_PERSONAL_ACCESS_TOKEN: ${{ vars.GITHUB_PERSONAL_ACCESS_TOKEN  }}

jobs:
  build:

    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup PHP with latest versions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: 'Create env file'
        run: |
          touch .env
          echo PROJECT_NAME="\"${PROJECT_NAME}\"" >> .env
          echo API_KEY="\"${API_KEY}\"" >> .env
          echo BITBUCKET_EMAIL="\"${BITBUCKET_EMAIL}\"" >> .env
          echo BITBUCKET_TOKEN="\"${BITBUCKET_TOKEN}\"" >> .env
          echo CONFLUENCE_SPACEKEY="\"${CONFLUENCE_SPACEKEY}\"" >> .env
          echo CONFLUENCE_URL="\"${CONFLUENCE_URL}\"" >> .env
          cat .env
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run PHP Script
        working-directory: src
        run: php index.php
      - name: PR Review
        working-directory: src
        run: |
          echo PR_REVIEW="true" >> .env
          echo OWNER_AND_REPO_NAME="\"${{ github.repository }}\"" >> .env
          echo PR_NUMBER="\"${{ github.event.number }}\"" >> .env
          echo GITHUB_PERSONAL_ACCESS_TOKEN="\"${GITHUB_PERSONAL_ACCESS_TOKEN}\"" >> .env
          php index.php
